# build data set from JSON files
name: pnyn-clean-build-dataset

on:
  workflow_dispatch:
  push:
    paths:
      - '**.json'  # only when the JSON files are updated      

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: build data set
          run: |
            # pre-check          
            pwd
            ls
            tree

            rm --help
            
            rm -rfv docs/*.txt
            rm -rfv docs/*.min.json            

            for f in docs/*.json; do 
              tag=$(basename -s .json $f); 

              echo 'minify JSON files ...'
              cat $f | jq -c > docs/$tag.min.json; 

              echo 'creating text files ...'
              cat $f | jq -r 'to_entries[] | "\(.key) \(.value)"' > docs/$tag.txt; 
            done;

            # post-check
            pwd
            ls
            tree
            
        - name: setup git config
          run: |
            pwd
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"

        - name: commit
          run: |
            pwd

            git pull
            git add .

            if [[ -z $(git status -s) ]]; then
              echo "nothing new..."
            else
              git commit -m "Auto-generated by MOTETFLOW."
              git push origin main              
            fi
